### ISSUE TITLE
Non standard Atom date format

### ISSUE THREAD

**Issue by shavounet** [alexdebril/feed-io#102]
When exposing new atom feed, it uses by default a non standard data format (`\DateTime::RFC2822`), instead of `\DateTime::ATOM`.

See http://php.net/manual/en/class.datetime.php#datetime.constants.atom

**Comment by alexdebril** [comment]
Thank you for your feeback, I just fixed and merged your pull request

**Comment by shavounet** [comment]
Oh I've haven't seen the unit tests, sorry !

BTW, I just fixed the issue I had (since I only use the atom format), but I didn't check others (which also don't seem to have the constant overridden).
No time to check the standards, but I hope it helps !
