### ISSUE TITLE
Configuring Guzzle or Monolog via \FeedIO\Factory does not work

### ISSUE THREAD

**Issue by mirfilip** [alexdebril/feed-io#105]
Hi!,

### Versions affected
I'm using newest stable (`3.0.1`) release of the library. It's irrelevant though, as the problem occurs in all previous versions.

### Background 
I'm using `\FeedIo\Factory::create` to create standard `FeedIo` instance:
```php
$feedIo = \FeedIo\Factory::create(
        [
            'builder' => 'Monolog',
            'config' => [],
        ]
    )->getFeedIo();
```

It works fine this way. The design of passing config indicates that you should be able to specify `Monolog\Logger` or `GuzzleHttp\Client` config under `config` key and `\FeedIo\Factory` should pass the to specific builders, then to actual class. This does not happen.

Examples suggest this is the intended case for configuration:
```php
$feedIo = \FeedIo\Factory::create(
        [
            'builder' => 'Monolog',
           'config' => [
                'test' => 'This should be passed to Monolog Logger constructor',
            ],
        ],
        [
            'builder' => 'GuzzleClient',
            'config' => [
                'test' => 'This should be passed to Guzzle Client constructor',
            ],
        ]
    )->getFeedIo();
```

### Problem
There are two problems.
1. MonologBuilder. Reflection API in `\FeedIo\Factory::getBuilder` is used incorrectly. `newInstanceArgs` takes an array an passes members one by one to the constructor. It does not pass the whole array to class constructor. `\FeedIo\Factory\Builder\MonologBuilder::__construct` is prepared to inject an array. To pull this off, this is how you'd have to craft your config:
```php
$feedIo = \FeedIo\Factory::create(
        [
            'builder' => 'Monolog',
            'config' => [
                'config' => [
                    'test' => true,
                ]
            ],
        ]
    )->getFeedIo();
```

2. GuzzleClientBuilder. It is not ready to be constructed with params (there is no constructor to capture the config and pass it to Guzzle Client). If you do:
```php
$feedIo = \FeedIo\Factory::create(
        [
            'builder' => 'Monolog',
            'config' => [
            ],
        ],
        [
            'builder' => 'GuzzleClient',
            'config' => [
                'config' => [
                    'test' => true,
                ]
            ],
        ]
    )->getFeedIo();
```
you get `PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class FeedIo\Factory\Builder\GuzzleClientBuilder does not have a constructor, so you cannot pass any constructor arguments' `. There is no workaround for that.

### Discussion
I can easily fix this but I need your acknowledgement that it's an oversight.

**Comment by alexdebril** [comment]
Hi,

Thank you very much for this excellent feedback, really easy to understand. I can confirm that I didn't covered every cases through the unit tests when I first wrote the factory. 

If you have the possibility to fix it I'll be happy to read your pull request, otherwise I'll take care of it in the next few days.

Thanks

**Comment by mirfilip** [comment]
Let me tackle that now as I needed to override Factories / Builders myself anyway. Thanks for fast feedback!

BTW. I'm about to create issues / contribute couple more as I dug under using your otherwise nicely designed little lib. Thx for creating it.
