### ISSUE TITLE
The Formatter does not handle multiple categories

### ISSUE THREAD

**Issue by shavounet** [alexdebril/feed-io#106]
When adding multiple categories to a \FeedIo\Feed, they are not outputed by the formatter.
Note that I use the 'Atom' format.

Test Case
------------

```
        $feed = new Feed();

        foreach ($this->newsList as $news) {
            $item = $feed->newItem();

[...]

            $fieldCategory = new Category();
            $fieldCategory->setScheme('field');
            $fieldCategory->setTerm([...]);
            $fieldCategory->setLabel([...]);
            $item->addCategory($fieldCategory);

            $sectorCategory = new Category();
            $sectorCategory->setScheme('sector');
            $fieldCategory->setTerm([...]);
            $fieldCategory->setLabel([...]);
            $item->addCategory($sectorCategory);

            $feed->add($item);
        }
```

Output
---------

```
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
[...]
    <entry>
        <title>[...]</title>
        <category scheme="field" term="[...]" label="[...]"/>
        <link href="[...]"/>
        <id/>
        <updated>2017-07-11T12:02:36+02:00</updated>
        <content>[...]</content>
    </entry>
```

It should have to "category" elements.

**Correction hints**
I think it may come from how rules are handles:
* `\FeedIo\Formatter::buildElements` expects one element by rule
* `\FeedIo\Rule\Category::createElement` takes only the 1st category

**Comment by alexdebril** [comment]
Hi,

Thank you for your feedback, it's crystal-clear. The solution to solve this is to refactor the way `RulesAbstract` generates elements, it should return a DomNodeList instead of a DomElement.

This is a huge refactoring but I think the pain is necessary, I'll try to do it in the next days or weeks.

Thanks,
