### ISSUE TITLE
Counting number of items in feed

### ISSUE THREAD

**Issue by mirfilip** [alexdebril/feed-io#108]
`FeedInterface` brings "iterability". `Feed` keeps all items in private member `$items`. In order to know the number of items one currently has to do:
```php
echo count($feed->toArray()['items'])
```

Sure, it works but it's a little overkill as it has to extract all the items to array. This is potentially resource consuming for more-than-usual nested items.

My idea would be to add `\Countable` interface to `FeedInterface` and below implementation to `Feed`:
```php
    public function count()
    {
        return count($this->items);
    }
```

This seems coherent with the fact iterating through feed gives you particular items.

I have the PR ready, waiting for your blessing.

**Comment by alexdebril** [comment]
It sounds good to me, you can submit the pull request.

Thanks !

**Comment by alexdebril** [comment]
closed by https://github.com/alexdebril/feed-io/pull/110
