### ISSUE TITLE
FeedIO client does not cache by default

### ISSUE THREAD

**Issue by mirfilip** [alexdebril/feed-io#109]
Hi!

In readme you state:
> HTTP Headers support when reading feeds in order to save network traffic
does this imply caching requests/responses?

As it stands, Guzzle6 isn't configured with [caching middleware](https://github.com/Kevinrob/guzzle-cache-middleware) and thus doing any kind of polling actually ignores HTTP caching headers.

Am I missing sth?

**Comment by alexdebril** [comment]
Hi,

You're right, I think FeedIo\Adapter\Guzzle\Client did handled the Last-Modified header a long time ago and now the feature is quite gone... The feature itself didn't imply caching results, it was just using HTTP headers to get a 304 if the feed wasn't modified.

First thing to do is to restore this 'Last-Modified' header, then I will think about this caching middleware.

**Comment by mirfilip** [comment]
It is my understanding too. [Guzzle3 used to handle that](https://github.com/guzzle/guzzle3/search?utf8=%E2%9C%93&q=Last-Modified&type=). With Guzzle6, it's delegated to middleware I mentioned.

Currently, no cache control mechanisms are used. I suggest you don't write your own 'Last-Modified' control as it's all handled [here](https://github.com/Kevinrob/guzzle-cache-middleware). As this is a really important mechanism and your lib is widely used, I'd suggest always depending on this middleware.

Maybe there could be a config option to turn off caching and based on that you could conditionally add this middleware to handler stack in `GuzzleClientBuilder`.

**Comment by alexdebril** [comment]
OK, this is worth giving a try. Do you expect me to write it or are you willing to submit a pull request ?

**Comment by mirfilip** [comment]
I can have a look on it later today. If I don't PR within 2 days, just take over the issue.

**Comment by alexdebril** [comment]
I think I'll take over the issue as I'd like to apply PSR-2 code style before (see https://github.com/alexdebril/feed-io/issues/114)

Did you start something on this ?

**Comment by mirfilip** [comment]
No, go ahead 👍

**Comment by alexdebril** [comment]
I will make two PRs to handle the following use-cases :

## As a developer I want to fetch only the newest items since my last hit. If the response's status is 304, it means the feed doesn't have any new item.

This is the main goal of the HTTP headers usage. Invoking `FeedIo::read()` with a `$modifiedSince` argument means we will get only the newest items since that date. If the response's status is 304, there is no item to fetch.

For that, I will only add the `if-modified-since` header to the request and handle the empty response.

## As I developer I want to cache results if I hit the same feed several times

For that purpose I will use the [cache middleware](https://github.com/Kevinrob/guzzle-cache-middleware)

**Comment by alexdebril** [comment]
This issue will cover the first use-case, the second one will be covered through #116

**Comment by mirfilip** [comment]
According the two scenarios you wrote, let me express how I see it. Maybe it proves handy somehow.

There are two kinds of caching that could potentially be handled:
- [conditional HTTP GET support](https://fishbowl.pastiche.org/2002/10/21/http_conditional_get_for_rss_hackers/) This is checking `Last-Modified` header and adding `If-Modified-Since` to the request of `readSince`.
- standard caching using `Cache-Control: max-age`. A sane RSS server should return this header to hint about average frequency of feed changes. If the feed refreshes rarely, it could easily instruct clients to cache for e.g. 5 minutes. This is where caching responses in memory comes handy.

`Feed` has two methods for reading `read` and `readSince`. As a new user of this library, I read the docs and assumed caching is baked in (thus this issue). I expected both `read` and `readSince` to interpret server headers and play along.

If you end up handling second type of cache, some kind of `force` parameter could come in handy. Consider this: client makes a request at time X -> RSS server returns `Cache-Control: max-age=300` -> client assumes the response is going to be the same withing (X; X+300) time frame -> client should be able to force requesting a fresh state even before 5 minutes elapse.

One way to tackle that would be to add some option `force` to both `read` and `readSince`.

**Comment by alexdebril** [comment]
Really interesting, I didn't have the Cache-Control in mind before. I'll take a few days to think about your last comment and to figure out a good solution for it. Meanwhile if something comes to your mind, feel free to share it.

Thanks !

**Comment by mirfilip** [comment]
One more thing to consider. Your change #117 brings conditional requests (at least from `Guzzle/Client`). 

When RSS server supports conditional GET, response should be empty. However, you can add `If-Modified-Since` to the request and have server totally disregard it and return a collection full of items - it happens when servers don't support it. A nice little addition would be then to iterate over items and compare `pubDate` to `$modifiedSince`. After all, result already has a response and modifiedSince params.

**Comment by alexdebril** [comment]
You're absolutely right, the feed is unmodified if the status code is 304 and the body is empty. Otherwise feed-io must use its classical filtering system. 
I'll open an issue for that.
