### ISSUE TITLE
The feed is unmodified if HTTP response's status is 304 AND the body is empty

### ISSUE THREAD

**Issue by alexdebril** [alexdebril/feed-io#119]
As @mirfilip said : 

> When RSS server supports conditional GET, response should be empty. However, you can add If-Modified-Since to the request and have server totally disregard it and return a collection full of items - it happens when servers don't support it. A nice little addition would be then to iterate over items and compare pubDate to $modifiedSince. After all, result already has a response and modifiedSince params.

**Comment by mirfilip** [comment]
You may want to consider [my comments](https://github.com/alexdebril/feed-io/commit/87599f010a01cdf8e9b9e7a9b3ca0e81ce29df34).
