### ISSUE TITLE
Date and timezone is not handled properly if feed timezone is different than script one

### ISSUE THREAD

**Issue by mirfilip** [alexdebril/feed-io#134]
### Background
I want to consume a feed I know is produced in a different time zone. For example purposes, let's say it's `America/Chicago`. The format of dates in the feed is `M d, Y g:i:s a` - not a standard one. Note, the date string doesn't have any timezone info.

Preparing the client:
```php
$feedIo->getDateTimeBuilder()->addDateFormat('M d, Y g:i:s a');
```
### Problem
I need to instruct FeedIO not to parse date strings as in a current script timezone but rather to treat them all as coming from the different one. I see [DateTimeBuilder has a public setter for timezone](https://github.com/alexdebril/feed-io/blob/master/src/FeedIo/Rule/DateTimeBuilder.php#L165), so I assume that's the thing to use.

If I don't set the timezone myself and rely on `DateTimeBuilder` to [read it from PHP settings](https://github.com/alexdebril/feed-io/blob/master/src/FeedIo/Rule/DateTimeBuilder.php#L62), the date string is interpreted as coming from my script's timezone.

On the other hand, if I register a different timezone:
```php
$feedIo->getDateTimeBuilder()->setTimezone(new \DateTimeZone('America/Chicago'));
```
and then read the RSS, this is what happens:
1. [Date string is used to create a `DateTime` object](https://github.com/alexdebril/feed-io/blob/master/src/FeedIo/Rule/DateTimeBuilder.php#L120). As `DateTimeZone` setting is not used [when constructing DateTime object](\DateTime::createFromFormat), the script timezone is used.
2. [A custom timezone I set is applied on DateTime object](https://github.com/alexdebril/feed-io/blob/master/src/FeedIo/Rule/DateTimeBuilder.php#L149). If you didn't override timezone in builder, it's the same timezone so you don't see a time shift. Nonetheless, if you do, `DateTime` object state is going to be changed.

For example, if I get `Aug 02, 2017 2:21:29 AM` string from RSS and set `America/Chicago` timezone for builder, I should get a `DateTime` object that corresponds to Unix timestamp `1501658489`:
```php
$dateString = 'Aug 02, 2017 2:21:29 AM';
$timezoneOfFeed = 'America/Chicago';

$dt = DateTime::createFromFormat('M d, Y g:i:s a', $dateString, new DateTimeZone($timezoneOfFeed));

echo $dt->format('U') . PHP_EOL; // 1501658489
```

It comes down to what `setTimestamp` does to `DateTime` object. Instead of "Take the original date string and reinterpret it using provided timezone", it's "Take the DateTime object (in timezone you've provided during construction) and tell me what date time that would be in provided timezone".

### Solution
I'm not 100% sure if it's a bug or a feature ~~but I don't see any value in it~~. It's good thing a resulting parsed feed keeps a `DateTime` object instead of a string but it's critical to interpret this flawlessly at parse time.

There are two ways to fix this:
1. As in my example, use third param of `DateTime::createFromFormat` and use timezone set in builder. Don't use `setTimezone` on already created `DateTime` as it's probably not what you want.
2. Don't allow setting custom timezone for builder to remove ambiguity. Make `\FeedIo\Rule\DateTimeBuilder::setTimezone` private. State in docs that date strings coming from feed will be interpreted in script timezone unless a string contains a timezone identifier.

Note, I don't say what happens when `\FeedIo\Rule\DateTimeBuilder::convertToDateTime` fails to guess a format and falls back to `\FeedIo\Rule\DateTimeBuilder::stringToDateTime`. It seems something similar is done there.

**Comment by alexdebril** [comment]
Thank you for this analysis, very accurate as usual.

From a "feed-io user" point of view, I don't want to deal with complicated stuff. I want to trigger `feedIo->read()` or `feedIo->readSince()`, get the feed to store it in database or whatever and that's it. Handling timezone is part of the complicated stuff, so basically I would choose the second solution for the sake of simplicity.

But from a "feed-io power user" point of view, I want to be able to face most situations especially those involving timezones. For that, I would need the first solution.

And from "feed-io's owner" point of view, it would have been so simple if everyone took care about standards when they wrote those damned invalid streams but unfortunately there's no solution for that :-)

Anyway, here's what I propose : to make users and power users happy, we could add an optional `Timezone` argument in feedIo::read() and feedIo::readSince(). If the argument exists, the given `timezone` will be used only for the next call and feedIo will take care of switching back to the default after that.

What do you think ?

**Comment by alexdebril** [comment]
As a consequence, FeedIo::read() would work like this (but in a clean way) : 

```php
    public function read($url, FeedInterface $feed = null, \DateTime $modifiedSince = null, \DateTimeZone $ts = null)
    {
        if (is_null($feed)) {
            $feed = new Feed();
        }

        if ($modifiedSince instanceof \DateTime) {
            $this->addFilter(new ModifiedSince($modifiedSince));
        }

       // a timezone is set, give it to the DateTimeBuilder
        if ($ts instanceof \DateTimeZone) {
            $defaultTs = $this->getDateTimeBuilder()->getTimezone();
            $this->getDateTimeBuilder()->setTimezone($ts);
        }
        
        $this->logAction($feed, "read access : $url into a feed instance");
        $result = $this->reader->read($url, $feed, $modifiedSince);

       // restore DateTimeBuilder's default value
        if(isset($defaultTs)) {
            $this->getDateTimeBuilder()->setTimezone($defaultTs);
        }

        $this->fixerSet->correct($result->getFeed());

        return $result;
    }
```

**Comment by mirfilip** [comment]
@alexdebril as it happens with that stuff, I wrote this issue yesterday, went home and realised what is done could easily be a valid use case.

By giving an option to set a custom timezone for a builder, you can convert date strings to custom timezone easily. So, if date string from feed has all the info (most importantly timezone identifier at the end), you can correctly provide a service of converting those to arbitrary timezone. Again, this may or may not be what people want - you will get different dates by comparing what a barebone http client returns (think curl) vs feedio.

Why that may be confusing? See an example of [php announce rss](http://news.php.net/group.php?group=php.announce&format=rss). It returns `pubDate` with timezone identifier, e.g. `Thu, 10 Nov 2016 15:15:43 -0500`. This is what happens:
```php
<?php
require 'vendor/autoload.php';

$dateTimeBuilder = new \FeedIo\Rule\DateTimeBuilder();
$pubDate = 'Thu, 10 Nov 2016 15:15:43 -0500';

$dateTime = $dateTimeBuilder->convertToDateTime($pubDate);

echo 'My local timezone is: ' . date_default_timezone_get() . PHP_EOL;
// My local timezone is: Europe/Oslo
echo $dateTime->format('Y-m-d H:i:s P') . PHP_EOL;
// 2016-11-10 21:15:43 +01:00
```

This is a default setting without fiddling with timezone. I'm not sure what's better - convert or not. In that particular case, I would expect a reader to preserve time as is, unless I ask it to apply my timezone. At *very* least, this should be clarified in docs.

I agree with what you wrote about simplicity - in majority of cases you don't even want to think about dates. The easiest way would be to take date strings and store them as strings. This wouldn't force interpreting/parsing it in timezone context, as it happens when you convert it to `DateTime`.

Also, the situation is even worse when different feeds return different formats, omit timezone identifier etc. On the other hand, feed-io already guesses formats, have fixers for different cases.

This is a list of what I would expect from a user-friendly RSS reader by default:

1. Don't mess with timezones at all. Don't apply script timezone if date string contains a timezone 
 identifier (this may be tricky to check). Result of reading a feed by feed-io and a barebone http client would then be the same in terms of dates. Maybe setting `DateTimeBuilder::setTimezone(null)` should mean "leave dates alone" and then never call `setTimezone` on `DateTime` objects. This could even be a default, but that would qualify for BC break.
2. Have a way of specifying that date strings should be treated as coming from particular timezone. This is what I wanted. Let's say: `DateTimeBuilder::setTimezone(new DateTimeZone('America/Chicago'))`. This should then use that timezone **when constructing `DateTime` objects**. 
3. Current behaviour of always using script timezone would be satisfied by user doing `DateTimeBuilder::setTimezone(new DateTimeZone(date_default_timezone_get()))`.

Again, I may be a power user and have different expectation from libs than usual user.

Still, I think the current behaviour of unconditionally applying a timezone is a bug when feed dates don't contain timezone identifier.

**Comment by alexdebril** [comment]
I forgot something about DateTimeBuilder yesterday before writing my answer, sorry my idea wasn't the solution you expected. Let's see how feed-io is designed and why : 
 
- dates are DateTime objects, not string, because it makes them easy to manipulate especially for date comparisons and storage. It allows the developer to use his/her own format in the application, which is very important if (s)he needs to store the date in database or apply rules based on it. If you decide to use date as strings given by feeds, you loose the ability to filter news and to store dates with a unique format.

 - the timezone is always set for filtering and comparisons. Let's say you have a date in EDT timezone in a feed and you save it without converting it in the server's timezone. And in my hypothesis, you completely ignore the notion of timezone so you don't store it neither. Later on, you will fetch that date from database then use it in readSince() arguments to filter items : the result will be wrong, you will have extra or missing items in your feed. Why : because the server will load the date with its own timezone, so `Thu, 10 Nov 2016 15:15:43 EDT` becomes `Thu, 10 Nov 2016 15:15:43 GMT` which is wrong. But if you convert the date in your own timezone before storing it, you will compare all the items' dates with `Thu, 10 Nov 2016 19:15:43 GMT`. Which is good because `Thu, 10 Nov 2016 15:15:43 EDT` = `Thu, 10 Nov 2016 19:15:43 GMT`, two different textual representations of the same value. That's why feed-io loads the date in feed's timezone, then converts the same date in the server's timezone.

To solve your problem we need to build the date provided by the feed in the feed's timezone. So you're right about constructing the DateTime object with the feed's DateTimezone as an argument, but only for feeds not providing the timezone. And then we still need to set the timezone to convert the date according to the server's configuration.

Not an easy patch, it will need some time.

**Comment by mirfilip** [comment]
- As wrote before, it's good feed-io parses date strings to `DateTime`. In majority of cases it's what you want. There are two cases where it becomes problematic: One, when returned date string has no timezone identifier (my case) but you know it from feed documentation. The only solution to mitigate that is to wrap all feed-io operations with setting custom (feed) timezone with `date_timezone_set` and bring back the original one after. Otherwise, it results in an incorrect parsing, see my previous examples. Second case is when you don't want your local timezone to interfere with the date strings, for whatever reason.

- [storing date time info in DB is a huge problem](https://derickrethans.nl/storing-date-time-in-database.html), we're just looking at the tip of an iceberg. Maybe, for major percentage of usages, you can get away with the use case you describe (storing in DB, date comparison, retrieval from DB, etc.). This is not the safest way though. The safest way is to bring any dates to UTC and work on timestamps ([1](https://stackoverflow.com/questions/2532729/daylight-saving-time-and-time-zone-best-practices/2532962#2532962)). This is the most versatile way in any high-level discussions without knowing the exact usage of feed-io.

Apart from above, I don't think we understood one another on what the root problem is.
This happens when you parse a feed that doesn't contain timezone identifier:
```php
$dateTimeBuilder = new \FeedIo\Rule\DateTimeBuilder();
$pubDate = 'Wed, 02 Aug 2017 07:21:29';

$dateTime = $dateTimeBuilder->convertToDateTime($pubDate);

echo 'Time from feed: ' . $pubDate . '. Timezone: -0500' . PHP_EOL;
// Time from feed: Wed, 02 Aug 2017 07:21:29. Timezone: -0500
echo 'My local timezone is: ' . date_default_timezone_get() . PHP_EOL;
// My local timezone is: Europe/Oslo
echo $dateTime->format('M d, Y g:i:s P') . PHP_EOL;
// Aug 02, 2017 7:21:29 +02:00
```
See, date string `$pubDate` without timezone identifier gets incorrectly interpreted as time in script timezone.

Setting timezone doesn't help:
```php
$dateTimeBuilder = new \FeedIo\Rule\DateTimeBuilder();
$pubDate = 'Wed, 02 Aug 2017 07:21:29';
$dateTimeBuilder->setTimezone(new DateTimeZone('America/Chicago'));
$dateTime = $dateTimeBuilder->convertToDateTime($pubDate);

echo 'Time from feed: ' . $pubDate . '. Timezone: -0500' . PHP_EOL;
// Time from feed: Wed, 02 Aug 2017 07:21:29. Timezone: -0500
echo 'My local timezone is: ' . date_default_timezone_get() . PHP_EOL;
// My local timezone is: Europe/Oslo
echo $dateTime->format('M d, Y g:i:s P') . PHP_EOL;
// Aug 02, 2017 12:21:29 -05:00
```
still incorrect.

I may be able to fix it by adding a string ` -0500` with all date fields of feed in some fixer. That's all it needs. But, I figured I would discuss the problem here as others may step in that problem without realising it.

**Comment by alexdebril** [comment]
This is what I understood : 

 - you hit a feed in which the date format doesn't include the time zone. Plus, the dates in this feed are not in UTC, so you get a different date when you construct a DateTime with it.
 - **you need an accurate value**. **When you get 'Wed, 02 Aug 2017 07:21:29' in your feed, you need to get 'Wed, 02 Aug 2017 07:21:29 -05:00' in memory**, or 'Wed, 02 Aug 2017 12:21:29 GMT'. Because both strings are different representations of the same value.

To illustrate how I separate date representation in feeds between the one on the server-side, let's play with php in interactive mode : 

```shell
php -a

php > $date = new \DateTime('Wed, 02 Aug 2017 07:21:29 -0500');
php > var_dump($date);
object(DateTime)#2 (3) {
  ["date"]=>
  string(26) "2017-08-02 07:21:29.000000"
  ["timezone_type"]=>
  int(1)
  ["timezone"]=>
  string(6) "-05:00"
}
php > echo $date->getTimestamp();
1501676489
php > $date->setTimezone(new DateTimezone('GMT'));
php > var_dump($date);
object(DateTime)#2 (3) {
  ["date"]=>
  string(26) "2017-08-02 12:21:29.000000"
  ["timezone_type"]=>
  int(2)
  ["timezone"]=>
  string(3) "GMT"
}
php > echo $date->getTimestamp();
1501676489
php > 
```
I didn't change $date's value. I changed its timezone in order to get $date's representation in my server's timezone, which is convenient when I need to print it or compare it with another date or whatever.

This is why the only solution when you get a date without a timezone, you need to construct the DateTime with a DateTimezone argument. To tell PHP "this is a Datetime as seen in Chicago". Changing the object's timezone afterward have no consequences on its value. It may have consequences on its string representation.

To illustrate that, you could patch feed-io as follow in your project's vendor/.

At https://github.com/alexdebril/feed-io/blob/master/src/FeedIo/Rule/DateTimeBuilder.php#L124

replace 

```php
$date = \DateTime::createFromFormat($format, $string);
```

with 

```php
$date = \DateTime::createFromFormat($format, $string, new \DateTimezone('EDT'));
```

Now you should get a valid Datetime. If you could make the test please, I would be curious to see the result

Thank you for your time

**Comment by alexdebril** [comment]
I think that https://github.com/alexdebril/feed-io/tree/issue/134 solves your problem.

How to use it (only with feeds in which the timezone is missing) : 

```php
$feedIo->getDateTimeBuilder()->setFeedTimezone(new \DateTimeZone($feedTimezone));
$result = $feedIo->read($feedUrl);
$feedIo->getDateTimeBuilder()->resetFeedTimezone();
```

You can get an explanation through sample code : https://github.com/alexdebril/feed-io/blob/issue/134/examples/force-timezone.php and https://github.com/alexdebril/feed-io/blob/issue/134/examples/missing-timezone.php

**Comment by mirfilip** [comment]
> you hit a feed in which the date format doesn't include the time zone. Plus, the dates in this feed are not in UTC, so you get a different date when you construct a DateTime with it.

Almost exactly. It doesn't matter if dates are in UTC, even if they were, `DateTimeBuilder` would parse them in local timezone context. That's part of the problem.

>This is why the only solution when you get a date without a timezone, you need to construct the DateTime with a DateTimezone argument. To tell PHP "this is a Datetime as seen in Chicago". Changing the object's timezone afterward have no consequences on its value. It may have consequences on its string representation.

Exactly, but you currently cannot do it with feed-io. Once a valid timezone is supplied when constructing `DateTime` object from string, further timezone changes doesn't change the timestamp, true.

Your patch is exactly what I suggested in my original post.

[Your fix](https://github.com/alexdebril/feed-io/commits/issue/134) solves the problem. It's the first way I suggested.

I see one problem though. [You've added a timezone param here](https://github.com/alexdebril/feed-io/commit/534dd95703f3673ef0777060947f0b3b7490915d#diff-b6f66eba72e23c3a11f70a75601a723eR129) but what about [DateTimeBuilder::stringToDateTime](https://github.com/alexdebril/feed-io/commit/534dd95703f3673ef0777060947f0b3b7490915d#diff-b6f66eba72e23c3a11f70a75601a723eR153)? IMO, it should behave the same way.

**Comment by alexdebril** [comment]
You're right, `stringToDateTime` should behave the same way. This method is the "last hope" to get a DateTime object from a non-standard date string, that's why I missed it.

Completely off-topic : which PHP version do you use in your projects ?

**Comment by mirfilip** [comment]
> Completely off-topic : which PHP version do you use in your projects ?
It varies widely. From 5.5.39 to 7.1. Upgrading is hard on hosting machines that are shared between projects. For some time now everything is containerized and easier this ways, so we pick what we really choose.

**Comment by alexdebril** [comment]
thank you for this information. Would you be interested in beta-testing feed-io fully migrated in PHP 7 ?

Concerning our DateTimezone issue, I'm planning to release the patch today, probably around 14:00 GMT+2.

**Comment by mirfilip** [comment]
Yes, I'm fine beta testing it as the time allows.

Thx, a pleasure working with you 👍

**Comment by alexdebril** [comment]
Thank you for your help :+1:

**Comment by alexdebril** [comment]
the fix (including stringToDateTime) is released
