### ISSUE TITLE
Not issue but question is it better than Zend Feed

### ISSUE THREAD

**Issue by rajjanorkar** [alexdebril/feed-io#149]
Hi Team,

I am currently using [Zend Feed](https://github.com/zendframework/zend-feed) so want to switch to this library, just would like to know is it better than zend-feed?

I have no idea about this library, i discovered it today.

Thank you.

**Comment by alexdebril** [comment]
Hi Raj,

This is an excellent question, I think it depends on what you want to do with, let's see some features you have in feed-io : 

 - Json Feed support  : https://jsonfeed.org/
- a Command line interface to read feeds
- it's PSR Compliant so you can log its actions using Monolog
- its design is based on Dependency Injection so you can use your own objects with feed-io's core classes

You can find the main documentation here :  https://feed-io.net/documentation.html

And if you need some help to use feed-io, feel free to open an issue on Github. 

Best regards,

**Comment by rajjanorkar** [comment]
Thanks for feedback @alexdebril 

I guess i should dig into the code and see how is the implementation you done here, but at the moment looks great, i need to look at different types of feeds this library support and encoding/decoding of feeds to utf-8.

You done awesome work @alexdebril keep it up.

**Comment by alexdebril** [comment]
Thank you very much for your support !

If you have special needs regarding encoding/decoding feeds, you could take a look at the filter system which allows you to process feed's items. And if it doesn't fit your needs, I'll be pleased to help you.

**Comment by alexdebril** [comment]
Hi @rajjanorkar ,

Can we close this issue now ? I hope you had an accurate answer to your question.

Thank you
