### ISSUE TITLE
getAuthor() return false

### ISSUE THREAD

**Issue by hakimihamdan88** [alexdebril/feed-io#156]
```
foreach ($result->getFeed() as $item) {
$item->getAuthor();
}
```
returning empty on https://mashable.com/feed/

but when using Zend Feed, 
```
$item->getAuthor()['name']
```
is returning the author name

**Comment by alexdebril** [comment]
Hi,

You can expect this bug to be fixed in 3.0.9 and ported in 4.1.1 very soon (during the first week of 2018)

Thank you for your feedback.
