### ISSUE TITLE
feed-io produces invalid RSS feeds

### ISSUE THREAD

**Issue by alexdebril** [alexdebril/feed-io#171]
following https://github.com/alexdebril/rss-atom-bundle/issues/170

feed-io produces invalid feeds as we can see through https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Frss-atom-demo.herokuapp.com%2Frss%2Fmock

main errors are : 

 - `<guid>` should not be declared in the channel, neither `<lastPubDate>`
 - Missing atom:link with rel="self"

Other validation problems may be added in the following issue.

**Comment by alexdebril** [comment]
RSS Feeds are now valid : https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Frss-atom-demo.herokuapp.com%2Frss%2Fmock

**Comment by cf-nsousa** [comment]
Feeds are not valid again: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Frss-atom-demo.herokuapp.com%2Frss%2Fmock

**Comment by alexdebril** [comment]
the demo is not up to date with the last feed-io release. Try with a fresh project, you'll have an accurate result

**Comment by cf-nsousa** [comment]
Oh ok my bad then ;) Unfortunately, I can't have the latest build since our project is not PHP7+ yet :/
Just by chance, do you know a way to make v4.1.1 valid without Forking and making changes xD
Problems are the same as the link: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Frss-atom-demo.herokuapp.com%2Frss%2Fmock

**Comment by alexdebril** [comment]
no problem, I corrected my comment :)

I can backport the fix to the 3.x branch of feed-io as it is supported until the end of php 5.6. Just to be sure, you're using feed-io through rss-atom-bundle in a Symfony project ?

**Comment by cf-nsousa** [comment]
No, I can update only feed-io if needed ;)

**Comment by alexdebril** [comment]
ok, great I will release it in the next few days. I'll tell you when it's ready :)

**Comment by cf-nsousa** [comment]
Nice, thanks ;) I'll await your call then :)

**Comment by alexdebril** [comment]
Hi @cf-nsousa 

The fix is now available in v3.1.1 ! 

Sorry for the delay

**Comment by cf-nsousa** [comment]
Hi @alexdebril ,
Thanks you!

No problem really ;)
