### ISSUE TITLE
How to make feed-io use a custom User-Agent string with the Guzzle client?

### ISSUE THREAD

**Issue by kwebble** [alexdebril/feed-io#173]
For a [feed](https://www.scientias.nl/feed/) I want to retrieve the client must send a `User-Agent` header that does not identify a known web browser. Web browsers first get a cookie wall before access is allowed. Other clients can access the feed directly. For example the [Feed Validator](https://validator.w3.org/feed/) has no problem with this feed.

I have tried creating a client with a custom user agent:

        $client = new \GuzzleHttp\Client([
            'headers' => ['User-Agent' => 'Myfeedreader 0.2']
        ]);

        $this->feedIo = new FeedIo(new Client($client), $logger);

But this returns the web page, not the feed. Debugging the request I saw this user agent was used:

    Mozilla/5.0 (X11; U; Linux i686; fr; rv:1.9.1.1) Gecko/20090715 Firefox/3.5.1

This is feed-io's default value. When I temporarily replaced it with my custom one the feed was retrieved successfully. 

My question: is there a way to define a custom user agent header to perform a request?

**Comment by alexdebril** [comment]
HI,

Thank you for your feedback and sorry for the delay.

The User-Agent should be specified through `FeedIo\Adapter\Guzzle\Client` 's constructor to let you configure it.

Not a big deal, I can do it very soon.

**Comment by kwebble** [comment]
Thanks for looking into it. As a temporary solution I changed `getResponse()` in `FeedIo\Adapter\Guzzle\Client`:  

    $options = $this->getOptions($modifiedSince);

    // Use configured user agent if provided.
    if (FALSE === strpos($this->guzzleClient->getConfig('headers')['User-Agent'], 'GuzzleHttp/')) {
        unset($options['headers']['User-Agent']);
    }

    return new Response($this->guzzleClient->request('get', $url, $options));

The intention is to let feed-io only override the user agent if the value of the Guzzle client looks like the default value used by Guzzle. 

Don't know how this fits with the rest of feed-io's code, but it works for me. And the constructor definition can stay the same.

**Comment by alexdebril** [comment]
Hi,

I just wrote an example of user-agent management at runtime : https://github.com/alexdebril/feed-io/blob/c22ab80b6ca9c9af08373f3e6343ded763edcf74/examples/change-user-agent.php

Injection of a custom User-Agent + a `setUserAgent()` method will allow everyone to override the default User-Agent through configuration and change it at anytime.

It will be available in the next release.
