### ISSUE TITLE
Need to get the first elements

### ISSUE THREAD

**Issue by jebog** [alexdebril/feed-io#174]
hey, thanks for your package, is there a way to get the first element (the new one) in feeds from the iterator ?

**Comment by alexdebril** [comment]
Hi, you're welcome !

By "the new one", do you mean when you are reading a feed ? If so, it can be filtered using the `ModifiedSince` argument, like in this example : https://github.com/alexdebril/feed-io#reading

You can also read the "Reading feeds" section of the documentation : https://feed-io.net/documentation.html

**Comment by jebog** [comment]
Thanks you

**Comment by alexdebril** [comment]
You're welcome !
