### ISSUE TITLE
Valid XML feed cannot be parsed

### ISSUE THREAD

**Issue by kwebble** [alexdebril/feed-io#175]
Parsing http://ravon.plumit.nl/Actueel/Nieuws/rss/1485 throws a `LogicException`: "*this document is not a XML stream*".

The feed data looks valid XML. When opened in Firefox the items are shown and the [Feed Validator](https://validator.w3.org/feed/) shows no errors.

It has something to do with the `isXml()` method in `FeedIo\Reader\Document` returning `FALSE`.

When I remove the call to `isXml()` in `loadDomDocument()` the feed is parsed and the items are found.

**Comment by alexdebril** [comment]
I found the cause of the issue. The stream starts with a BOM character, I just needed to remove it from the string and everything just works fine.

Fixed very soon in the next release
