### ISSUE TITLE
Add support of attributes on feed level.

### ISSUE THREAD

**Issue by olysyuk** [alexdebril/feed-io#191]
Currently it's not possible to set ```xmlns:media="http://search.yahoo.com/mrss/"``` on top level of feed. And each ```media:*``` item has to include this attribute that leads to increased feed size.
```
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:media="http://search.yahoo.com/mrss/">
</rss>
```

Is it possible to set xmlns on top level?

**Comment by alexdebril** [comment]
For that, you need to use the Formater directly, like this : 

```php
<?php

require __DIR__.DIRECTORY_SEPARATOR.'bootstrap.php';

use \FeedIo\Factory;
use \FeedIo\Feed;

$feed = new Feed();

$feed->doWhatever()->youNeed()->with()->yourFeed();
$feedIo = Factory::create()->getFeedIo();
$formatter = $feedIo->getStandard('rss')->getFormatter();

$dom = $formatter->toDom($feed);

```
`$dom` is a `DomDocument` instance, you'll be able to do whatever you want to it.
