### ISSUE TITLE
LastModified

### ISSUE THREAD

**Issue by meradoou** [alexdebril/feed-io#192]
Hello,
I created a mini rss reader but I have a problem when I retrieve feed's content. I start to sync http://feeds2.feedburner.com/LeJournalduGeek (example), I get a correct lastModified and I store the value on db . When I use the lastModified value (from db), I get new lastModified but like this "1970-01-01 00:00:00.000000"

```
$resource = $this->container->feed->readSince($feed->url, new \DateTime($feed->synced));
$document = $resource->getFeed();
            
$lastModified = $document->getLastModified(); // 1970-01-01 00:00:00.000000 on second sync
```

**Comment by alexdebril** [comment]
Hello,

Have you dumped `$feed->synced` to see if its value is correct ?

You can try [https://github.com/alexdebril/feed-io/blob/master/examples/modifiedSince.php](this example) for instance. I used the URL you provided and I get this output : 

```
php examples/modifiedSince.php
feed title : Journal du Geek 
 [Bon Plan] Retour du forfait Free Mobile à 0,99€/mois, mais… : 2018-09-12T19:59:35+00:00
Pas d’iPhone 9 cette année, mais un iPhone XR, plus abordable : 2018-09-12T18:48:20+00:00
Apple annonce les iPhone XS, XS Max : une évolution sans véritable surprise : 2018-09-12T18:28:09+00:00
Plus grande, plus spacieuse, voici la nouvelle Apple Watch Series 4 : 2018-09-12T17:42:56+00:00
[Bon Plan] KingDian P10 : un petit SSD portable à partir de 37€ : 2018-09-12T15:00:32+00:00
[Bon plan] Forfait RED by SFR 30 Go pour 5€ par mois à vie ! : 2018-09-12T13:29:25+00:00
[Bon Plan] Le OnePlus 6 (64Go/6Go) à 386€ ! : 2018-09-12T13:10:07+00:00
iPhone XS : combien de temps faut-il attendre pour les payer moins cher ? : 2018-09-12T12:41:02+00:00
Amazon : Quand l’entreprise imagine une “cage” pour ses employés : 2018-09-12T12:15:52+00:00
La date de mise en vente des nouveaux iPhone déjà dévoilée ? : 2018-09-12T10:45:36+00:00
```

**Comment by meradoou** [comment]
Hello,
I use timestamp type on mysql (like that 2018-08-13 13:05:27) .

**Comment by alexdebril** [comment]
Hello,

Guess what ? It's a bug and I finally found a solution. I didn't believed it in the first place, but there's an issue in the way feed-io deals with RSS dates. Just because an argument is not properly sent to `RuleSet->add()`.

And thank you very much for your patience, the patch is coming today.
