### ISSUE TITLE
Design Academy Feed not working

### ISSUE THREAD

**Issue by jkniest** [alexdebril/feed-io#197]
Dear Feed IO Team / Community,

I have used this library successfully to read a lot of different feeds. But unfournatley the feed: "https://designacademy.io/feed/" isn't working. In other rss readers it's working perfectly.

The exception which gets thrown is: `malformed xml string. parsing error : DOMDocument::loadXML(): CData section not finished <div class="post-intro-text"> <p>In January 2018, in Entity, line: 382 (2)`

But as far as I can see it, the CDATA Object is closed at the end. 

Thanks in advance,
Jordan

**Comment by alexdebril** [comment]
Hello Jordan and Thank you for this feedback.

Fortunately this bug is fixed since https://github.com/alexdebril/feed-io/pull/196, so you just need to update feed-io to v4.3.5.

I checked using the console, the bug occurs with v4.3.4 but not in v4.3.5 anymore.

```
./vendor/bin/feedio read  https://designacademy.io/feed/
```

**Comment by jkniest** [comment]
Thank you! It works perfectly now.
