### ISSUE TITLE
Setting Link `rel`, `type`, `title` in Atom feeds

### ISSUE THREAD

**Issue by karllhughes** [alexdebril/feed-io#201]
I found that I can set a `link` in a feed or item, but I can't figure out how to set the `rel`, `type`, or `title` attributes as outlined in the Atom feed spec: https://validator.w3.org/feed/docs/atom.html#link

Am I missing something or is this feature currently unavailable?

**Comment by alexdebril** [comment]
This feature is currently unavailable, this is because feed-io offers the ability to write RSS or Atom feeds using the same API.

But it leads me to a big question : should feed-io drop RSS writing support and focus on Atom + JsonFeed to offer more abilities for advanced users ?

**Comment by karllhughes** [comment]
Interesting.

You could drop RSS support, but that seems like a big, breaking change. Maybe you could offer some sort of lower-level attribute access. For example, if I could set node attributes, I could add them to the underlying object, but the `toRss()` method might just ignore them.

If a goal of this project is to allow advanced Atom/RSS feed creation, it would be good to allow full use of the specifications' features.

But, if the goal is a higher-level, "best fit" abstraction, then you don't have to worry about it. It's definitely more a case for power users.

**Comment by alexdebril** [comment]
closing, as there's no other request for that feature. However, I'll provide some doc on how to extend feed-io to do it.

thanks for that feedback
