### ISSUE TITLE
3.1.2 tag is based on the 4.0 branch

### ISSUE THREAD

**Issue by SMillerDev** [alexdebril/feed-io#207]
When trying to download 3.1.2 on a php 7.0 instance, which the 3.x branch should be compattible with, composer fails. https://travis-ci.org/nextcloud/news/jobs/505123738

**Comment by alexdebril** [comment]
really sorry, I forgot to select the branch while releasing. It's fixed with V3.1.3 https://packagist.org/packages/debril/feed-io#v3.1.3

**Comment by SMillerDev** [comment]
Thanks a lot for helping, it's not a problem at all.
