### ISSUE TITLE
documentElement is array

### ISSUE THREAD

**Issue by jknockaert** [alexdebril/feed-io#208]
I am getting php errors:
```
Trying to get property 'tagName' of non-object at debril/feed-io/src/FeedIo/Standard/Atom.php#54
Trying to get property 'tagName' of non-object at debril/feed-io/src/FeedIo/Standard/Rss.php#54
Trying to get property 'tagName' of non-object at debril/feed-io/src/FeedIo/Standard/Rdf.php#54
```
The issue is that `$document->getDOMDocument()->documentElement` is an array, so it doesn't have properties. I am however not sure how to fix that.
I am working with the 3.0 branch.

**Comment by alexdebril** [comment]
This is really weird, could you provide the feed's URL and the code block concerned please ?

**Comment by jknockaert** [comment]
The error went again. So am not sure what feed caused it. Will report back once it resurfaces.

**Comment by alexdebril** [comment]
hi @jknockaert 

Did you experienced the issue again lately ? If not, I invite you to close the issue and eventually open it again if it resurfaces.

Thanks

**Comment by jknockaert** [comment]
@alexdebril OK.
