### ISSUE TITLE
Relative links are not feed-relative

### ISSUE THREAD

**Issue by heyarne** [alexdebril/feed-io#210]
I opened this issue first in https://github.com/nextcloud/news/issues/472 and was redirected here. To quote:

> ## Explain the Problem
> Relative links in feeds viewed in the web interface are not feed-relative but point to the nextcloud instance hosting the app.
> 
> ## Steps to Reproduce
> Explain what you did to encounter the issue
> 1. Subscribe to https://blog.fefe.de//rss.xml?html
> 2. Click on any link pointing to another blog post (search for "/?ts=)

**Comment by alexdebril** [comment]
Like in this one ? 

```xml

<description>Hmm, jetzt kommen so viele Optimierungen für <a href="/?ts=a2689de5">wp</a> rein, dass ich mich frage, ob wir vielleicht mal lieber einen Optimierungswettbewerb machen sollten. Performance scheint den meisten Leuten wichtiger zu sein als eleganter, idiomatischer Code :-)<p>OK dann sagen wir mal: stdin ist eine Datei (seek und mmap gehen) und ihr dürft Threads benutzen. Die Testmaschine hat vier Cores, davon zwei bloß Hyperthreading. Die Eingabedaten dürfen als ASCII-Bytes bearbeitet werden. Wer also Locale und UTF-8-Validierung für bessere Performance abschalten kann, darf das tun. Die Ausgabe geht in eine Datei, Flush bei Zeilenenden darf abgeschaltet werden.<p>Da bin ich mal gespannt, wie die verschiedenen Sprachen sich mit Multithreading schlagen.<p><b>Update</b>: Ich habe mal eine <a href="//ptrace.fefe.de/wp/wp-perf.cc">C++-mmap-Thread-Variante</a> gehackt, die kommt auf 1,7 Sekunden Wall Time. Nur um da mal den Ball zum Rollen zu bringen. Das könnte man bestimmt auch noch geschickter machen, Vorschläge nehme ich gerne entgegen. Ich hätte weniger Threading-Performancegewinn vermutet.<p><b>Update</b>: Mein Testrechner ist mein Reiselaptop, da ist wie gesagt ein N5000 drin — das ist ein Atom mit 5W TDP, passiv gekühlt, und auch die RAM-Anbindung ist auf Stromsparen und nicht auf Durchsatz ausgelegt. Das scheint hier in einige der Benchmarks reinzugrätschen und bei mir deutlich schlechtere Performancezahlen zu bringen als bei Einsendern zuhause, die auf dicken Xeons oder so arbeiten. Insbesondere Java scheint hier im Nachteil zu sein, aber auch bei Go gab es starke Diskrepanzen.</description>

```

**Comment by heyarne** [comment]
Yes, exactly. The URL should be relative to the item URL, I guess? I know this is kind of tricky, but my reasoning here is that the feed URL points to a location where the content in the `<description>` can be read in full; this would match the behavior of the link showing up at that location.

**Comment by alexdebril** [comment]
it's really tricky but yes, relative urls could be turned into absolute using the item's url. Provided this one is absolute :-]

**Comment by emichael** [comment]
+1 This would be great to see.

I also noticed issues with the Nextcloud news app. In my case, I noticed that images were broken (because they used relative srcs).

**Comment by RichardDern** [comment]
Wikipedia also uses relative URLs in their feeds (at least in the French feeds).

**Comment by alexdebril** [comment]
yes that's a pity and as a soon as a Pull Request comes I will be thrilled to review it :)
