### ISSUE TITLE
RSS content module

### ISSUE THREAD

**Issue by Grotax** [alexdebril/feed-io#211]
What is your current opinion on RSS modules?
We received some reports about feeds that no longer contain the full text.
The issue is that those feeds use the content tag that is defined in http://web.resource.org/rss/1.0/modules/content/
feed-io will only return the description.

The picofeed approach is simple, if content is found use it if not get description :)
https://github.com/aaronpk/picofeed/blob/master/lib/PicoFeed/Parser/Rss10.php#L238

**Comment by alexdebril** [comment]
My opinion is : feed-io needs more contributors :-]

It would be simple to implement, I think it should be added to feed-io.

**Comment by alexdebril** [comment]
Thank you for your pull request, I didn't realized it was just the 'content:encode' alias to set.

It's released in https://packagist.org/packages/debril/feed-io#v3.1.4, I let you close the issue if it's actually solved.

**Comment by Grotax** [comment]
Me too. I spend quite some time to figure this out 😀

**Comment by Grotax** [comment]
Fixed.

**Comment by paroj** [comment]
what happens if both `description` and `content:encoded `are present?

**Comment by Grotax** [comment]
`content:encoded` is selected and `description` is ignored.
