### ISSUE TITLE
[support] no more "limit" 

### ISSUE THREAD

**Issue by romaricdrigon** [alexdebril/feed-io#215]
Hello,

In old version (the one bundled with `DebrilRssAtomBundle`), a `Limit` filter was provided. It was removed and no drop-in is offered, correct? So it has to be implemented client-side?

**Comment by alexdebril** [comment]
Hello,

You can do it though the filter system. You define a new filter and add it to feedIo using `FeedIo\FeedIo::addFilter()`.

see: 
- https://github.com/alexdebril/feed-io/blob/master/src/FeedIo/FilterInterface.php
- https://github.com/alexdebril/feed-io/blob/master/src/FeedIo/FeedIo.php#L143

(not very well documented I admit)
