### ISSUE TITLE
Error 403 

### ISSUE THREAD

**Issue by meradoou** [alexdebril/feed-io#221]
Hi,
I get an error 403 for https://korben.info/feed . I try on my app and on https://feed-io.net/ :

```
{"type":"FeedIo\\Reader\\ReadErrorException","title":"Client error: `GET https:\/\/korben.info\/feed` resulted in a `403 Forbidden` response:\n\u003C!DOCTYPE html\u003E\n\u003Chtml lang=\u0022en\u0022 xmlns=\u0022http:\/\/www.w3.org\/1999\/xhtml\u0022\u003E\n\u003Chead\u003E\n\u003Clink rel=\u0022stylesheet\u0022 href=\u0022https:\/\/cdn.su (truncated...)\n"}
```

**Comment by alexdebril** [comment]
Hi,

There's a rule on https://korben.info which rejects the request if the user-agent matches an expected value. But I don't have any clue on this rule, I tried several user-agent and the only one that worked for me was "yolo".

I prefer not to update feed-io's code with such a value in it, it would be a good idea to know which user-agents are accepted by this site.

**Comment by meradoou** [comment]
Thank you.  I'll try several user agent.
