### ISSUE TITLE
[request] Support compression (gzip,brotli)

### ISSUE THREAD

**Issue by lord-re** [alexdebril/feed-io#228]
Most http server support compression (deflate, gzip, brotli and some others).

It may be interesting to support it to reduce the required bandwidth as it's often used to frequently poll for news.

**Comment by alexdebril** [comment]
Do you mean compressing the feed  produced by `feed-io` ? Isn't it something already supported by web servers like Nginx and Apache ?

**Comment by lord-re** [comment]
No, i meant when you are fetching a feed with http, adding an "accept-encoding: br" or any other compression method.
