### ISSUE TITLE
Plan a new release in order to spread #231 & 233

### ISSUE THREAD

**Issue by brunob** [alexdebril/feed-io#235]
What do you think about a new release in order to help nextcloud news team to get it back to work ? See https://github.com/nextcloud/news/issues/537 for the context ;)

**Comment by alexdebril** [comment]
I released 4.3.11 yesterday, isn't it OK?

**Comment by brunob** [comment]
Thx a lot and sorry for the noise, it seems i've missed the release :)

**Comment by alexdebril** [comment]
you're welcome :)
