### ISSUE TITLE
Media-RSS support

### ISSUE THREAD

**Issue by azmeuk** [alexdebril/feed-io#240]
Hi. Is there any plan to support the [Media-RSS specification](http://www.rssboard.org/media-rss#media-description)?
The specification is quite old, but youtube and peertube use it for their feeds ([youtube example](https://www.youtube.com/feeds/videos.xml?channel_id=UC7_gcs09iThXybpVgjHZ_7g), [peertube example](https://framatube.org/feeds/videos.xml?accountId=3)).

Éloi

**Comment by alexdebril** [comment]
Hi Eloi,

I think it's easy to add, just a new couple of getter/setter inside https://github.com/alexdebril/feed-io/blob/master/src/FeedIo/Feed/Item/MediaInterface.php + adapt the matching rule and it's set. Also, don't forget the tests.

Do you feel like submitting a Pull Request for this ?

**Comment by azmeuk** [comment]
My PHP is a bit rusty, but I might try. I preferred to check if the feature is welcomed first :)

**Comment by SMillerDev** [comment]
There is now a 15 dollar bounty on this feature in nextcloud/news

**Comment by azmeuk** [comment]
Yep. I set it :)

**Comment by azmeuk** [comment]
Just to add a bit of context, here is an extract of a [Youtube feed](https://www.youtube.com/feeds/videos.xml?channel_id=UC7_gcs09iThXybpVgjHZ_7g).

Here there is one `<media:group>` containing all the details.
```xml
<media:group>
    <media:title>Is Time Travel Impossible?</media:title>
    <media:content url="https://www.youtube.com/v/pGnMiGrYmPE?version=3" type="application/x-shockwave-flash" width="640" height="390"/>
    <media:thumbnail url="https://i1.ytimg.com/vi/pGnMiGrYmPE/hqdefault.jpg" width="480" height="360"/>
    <media:description>Sign Up on Patreon to get access to the Space Time Discord! 
https://www.patreon.com/pbsspacetime

Check out the Space Time Merch Store
https://pbsspacetime.com/

Time travel stories are cool because both the past and future are somehow more interesting that the present and because everyone wants a redo.  But so far it appears we’re doomed to live consumed by regret in the eternal, boring present. Time marches on, inexorably and only forward. Or so we thought until Einstein came along. His special and general theories of relativity changed the way we think about time forever, and believe it or not, their raw equations permit time travel. They even tell us how to do it. So let’s review the possibilities, and decide how possible they really are. [...]</media:description>
    <media:community>
        <media:starRating count="14205" average="4.93" min="1" max="5"/>
        <media:statistics views="349292"/>
    </media:community>
</media:group>
```

Here is an extract of a [Peertube feed](https://framatube.org/feeds/videos.xml?accountId=3). Here there is a `<media:group>` containing the same video in several resolutions, and a `<media:tumbnail>` tag. Reading the Media-RSS specifiaction, I think that the thumbnail should be part of the group tag, I think it is a bug from peertube and I will open a bug report there.

```xml
<media:group>
    <media:content type="application/x-bittorrent" url="https://framatube.org/static/torrents/ed5c048d-01f3-4ceb-97db-6e278de512b0-1080.torrent" isDefault="true"></media:content>
    <media:content type="application/x-bittorrent" url="https://framatube.org/static/torrents/ed5c048d-01f3-4ceb-97db-6e278de512b0-720.torrent"></media:content>
    <media:content type="application/x-bittorrent" url="https://framatube.org/static/torrents/ed5c048d-01f3-4ceb-97db-6e278de512b0-480.torrent"></media:content>
    <media:content type="application/x-bittorrent" url="https://framatube.org/static/torrents/ed5c048d-01f3-4ceb-97db-6e278de512b0-360.torrent"></media:content>
    <media:content type="application/x-bittorrent" url="https://framatube.org/static/torrents/ed5c048d-01f3-4ceb-97db-6e278de512b0-240.torrent"></media:content>
    <media:rating>nonadult</media:rating>
</media:group>
<media:thumbnail url="https://framatube.org/static/thumbnails/ed5c048d-01f3-4ceb-97db-6e278de512b0.jpg" height="122" width="223"></media:thumbnail>
```

**Comment by azmeuk** [comment]
For the record: Peertube has implemented more Media-RSS tags in their feeds: https://github.com/Chocobozzz/PeerTube/issues/2298

**Comment by azmeuk** [comment]
Hi @alexdebril 
I am currently working toward a better support for Media-RSS. There is something I would like your advice on. The specification [states this](http://www.rssboard.org/media-rss#optional-elements):

> Duplicated elements appearing at deeper levels of the document tree have higher priority over other levels. For example, &lt;media:content> level elements are favored over &lt;item> level elements. The priority level is listed from strongest to weakest: &lt;media:content>, &lt;media:group>, &lt;item>, &lt;channel>.

So in the following example with the `<media:description>` tag, the description `A` has priority over `B`, that has priority over `C`, that has priority over `D`.

```xml
<rss version="2.0" xmlns:media="http://search.yahoo.com/mrss/">
    <channel>
        <title>Title of page</title>
        <link>http://www.foo.com</link>
        <description>Description of page</description>
        <item>
            <title>Story about something</title>
            <link>http://www.foo.com/item1.htm</link>
            <media:group>
                <media:content url="http://www.foo.com/trailer.ogg">
                    <media:description>A</media:description>
                </media:content>
                <media:description>B</media:description>
            </media:group>
            <media:description>C</media:description>
        </item>
        <media:description>D</media:description>
    </channel>
</rss>
```
According to the specification, the only primary tags are `<media:group>` and `<media:content>`, so only they represent media objects. All the other `<media:*>` tags represent some metadata about medias.

So, it seems that I need to keep track of `<media:*>` tags that are direct children of `<channel>` and `<item>`, but not consider them as media objects, until a `<media:content>` or a `<media:group>` is found, and then "apply" the previous metadata to those media. Also if a tag in `<media:content>` conflicts with the same tag in the `<media:group>` parent, the deeper one should be kept.

I am not really sure how to implement this :) Do you have a clue on how to do that?

Thank you for your help

Éloi

**Comment by azmeuk** [comment]
I found a pretty elegant solution solution with XPaths, I hope I can submit a new pull request in a few days.

**Comment by alexdebril** [comment]
Hi Eloi,
Sorry I didn't get back to you earlier, though it's a very interesting topic. Just one thing: be careful with XPath, as it can have an impact on performances. So maybe it's better to use it only when the `media` node is a `media:group` in order to avoid impact on simple feeds.

**Comment by azmeuk** [comment]
Implemented in https://github.com/alexdebril/feed-io-extended-rss/pull/1
