### ISSUE TITLE
latin2 content encoding breaks feed-io read

### ISSUE THREAD

**Issue by mb-0** [alexdebril/feed-io#247]
Looks like an iso-8859-2 (extended latin) feed can break parsing and runs into a read error : No parser can handle this stream.

Easy repro: use any feed and replace head with"
```
<?xml version="1.0" encoding="iso-8859-2"?>
```
"Read". See error.
Changing that to iso-8859-1 makes it go away.

But note: should this come from a website where that's the default encoding, the content will also need to be converted with iconv to something like utf-8, otherwise it's gonna keep failing.

I see no mentioning of supported charsets in docs, makes me think this might be a bug to look at.

Thanks,
mb

**Comment by alexdebril** [comment]
Hi,

Do you have a live example please ?

**Comment by mb-0** [comment]
Hey Alex,

Yeah, this one here shows the symptoms nicely: https://bgds.hu/testrss.xml

mb

**Comment by alexdebril** [comment]
Hi,

It works with a recent version of feed-io:
```
 ./bin/feedio read https://bgds.hu/testrss.xml                                                                                                                                        
m2 aktuális műsora
```
(besides, the feed is empty)

**Comment by mb-0** [comment]
Great, thanks!
