### ISSUE TITLE
Tumblr RSS broken because of GDPR page redirection - need to change user agent?

### ISSUE THREAD

**Issue by Eliness** [alexdebril/feed-io#251]
Hi Alex (and everyone else!)

I noticed that feed-io (used by the News app in my Nextcloud instance) is unable to fetch any feed from Tumblr (eg. https://engineering.tumblr.com/rss ). I think this may be because the RSS URLs redirect now to https://www.tumblr.com/privacy/consent thanks to their weird way of dealing with GDPR.

One fix I found for several RSS readers is to change the user agent this way:
Baidu UA ("Mozilla/5.0 (compatible; Baiduspider; +http://www.baidu.com/search/spider.html)"
(source: https://www.cyberseo.net/gdpr-and-tumblr-rss-issue/)
Same for TTRSS, line 42 of the following plugin: https://github.com/GregThib/ttrss-tumblr-gdpr/blob/master/init.php

Would it be possible to implement this in feed-io, if indeed it helps to solve the issue?

Thank you!

**Comment by alexdebril** [comment]
Hi Eliness,

There's a way to specify which user-agent to send, you need to inject it to the Guzzle Http client like in this example: https://github.com/alexdebril/feed-io/blob/master/examples/change-user-agent.php

```php
$logger = new Logger('Logger');
$client = new \FeedIo\Adapter\Guzzle\Client(
    new GuzzleHttp\Client(),
    'Mozilla/5.0 (compatible; Baiduspider; +http://www.baidu.com/search/spider.html)'
);
$feedIo = new \FeedIo\FeedIo($client, $logger);

$result = $feedIo->read('http://php.net/feed.atom');
```

if you need to change the `user-agent`, you can access it through FeedIo's reader like this:

```php
$feedIo->getReader()->getClient()->setUserAgent($newUA);
```
I hope it's helpful to cover your case

**Comment by Eliness** [comment]
Works like a charm! Thank you very much :)
