### ISSUE TITLE
How to get content node

### ISSUE THREAD

**Issue by adsc-cloudtec** [alexdebril/feed-io#256]
I'm probably not understanding something fundamental, but I can't for the heck of it figure out how to get the actual content of the feed items. None of the examples seem to show how that's done. Am I supposed to implement my own classes that implement FeedInterface and ItemInterface to provide convenient methods to get what I want?

**Comment by alexdebril** [comment]
Hi,

See: https://github.com/alexdebril/feed-io#reading

and to get the item's content, just call `Item::getDescription()`

**Comment by adsc-cloudtec** [comment]
Oh man. I actually already used this method, but my feed has a `<div class="description">` in the content, so my stupid brain thought that's what the method is for. I didn't even check the value it grabbed :).

Why is the method named this way, though, when the element is called `<content>`? Is it because it's named differently in RSS spec?
