### ISSUE TITLE
Feed not working

### ISSUE THREAD

**Issue by tobiasKaminsky** [alexdebril/feed-io#265]
Hi, 

I am using nextcloud-news which is using this library.
For some reason one RSS feed fails, which I can reproduce here:

```
» bin/feedio read http://rss.kicker.de/news/2bundesliga
--> empty

bin/feedio read -c2 https://www.op-online.de/region/langen/rssfeed.rdf
op-online.de - Langen
2020-03-09T03:00:00+01:00 : Langener Stadtgeschichte: Eine Führung mit durchaus gewagten Thesen
Dass die Langener Stadtmauer vor Jahrhunderten nur zur Hälfte fertig geworden ist, weil den Auftraggebern das Geld ausging, ist eine kühne These, doch sie lässt sich wissenschaftlich belegen.
media found : https://www.op-online.de/bilder/2020/03/09/13585350/165347831-c42f768a-81c8-45ba-abe3-7da892e3feea1-1OOIixEbln01.jpg
2020-03-07T19:54:00+01:00 : CDU entsetzt: „Gift für den politischen Prozess“
```

Thanks for your great lib!

**Comment by kesselb** [comment]
I'm not sure if that is a feed-io issue :rofl: 

```
Index: src/FeedIo/Adapter/Guzzle/Client.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/FeedIo/Adapter/Guzzle/Client.php	(revision c651b6fc8952ebf0121bc0cc06ceeb3a69d482cf)
+++ src/FeedIo/Adapter/Guzzle/Client.php	(date 1583780812842)
@@ -136,6 +136,7 @@
     protected function getOptions(\DateTime $modifiedSince) : array
     {
         return [
+            'handler' => new \GuzzleHttp\Handler\StreamHandler(),
             'headers' => [
                 'User-Agent' => $this->userAgent,
                 'If-Modified-Since' => $modifiedSince->format(\DateTime::RFC2822)
```

If we tell Guzzle to use the `StreamHandler` (instead of the `CurlHandler`) reading the feed works. So that might be a issue with Guzzle or the feed itself. 

Here is a example https://gist.github.com/kesselb/34a522300f9e1ad772241b4cda66bb85. You need to run `composer require guzzlehttp/guzzle` in the same folder to install guzzle. I already asked the Guzzle community at https://gitter.im/guzzle/guzzle.

**Comment by tobiasKaminsky** [comment]
> I'm not sure if that is a feed-io issue rofl

Nextcloud -> feed-io --> Guzzle -> xy? I am sure the line will continue :see_no_evil: 

Thanks for helping!

**Comment by alexdebril** [comment]
I think I can submit a patch to fix it on feed-io's level, thanks @kesselb for finding this
