### ISSUE TITLE
Error: Impossible to convert date

### ISSUE THREAD

**Issue by timokoesters** [alexdebril/feed-io#271]
Hi, I'm using nextcloud news and this feed doesn't work: <https://blog.rust-lang.org/feed.xml>

Error:
Impossible to convert date : 2020-04-01T14:50:18.826492405+00:00

I asked around a bit and it seems like this is a problem of feed-io not supporting DateTime::RFC3339_EXTENDED.

**Comment by alexdebril** [comment]
Hi
I tried adding DateTime::RFC3339_EXTENDED in the supported format lists and it looks like "2020-04-01T14:50:18.826492405+00:00" is not a valid DateTime::RFC3339_EXTENDED

Also, look:

```php
php -a
Interactive mode enabled

php > $d = new \DateTime("2020-04-01T14:50:18.826492405+00:00");
PHP Warning:  Uncaught Exception: DateTime::__construct(): Failed to parse time string (2020-04-01T14:50:18.826492405+00:00) at position 0 (2): The timezone could not be found in the database in php shell code:1
Stack trace:
#0 php shell code(1): DateTime->__construct('2020-04-01T14:5...')
#1 {main}
  thrown in php shell code on line 1
php > $d = \DateTime::createFromFormat(\DateTime::RFC3339_EXTENDED, "2020-04-01T14:50:18.826492405+00:00");
php > var_dump($d);
php shell code:1:
bool(false)
php > var_dump(\DateTime::getLastErrors());
php shell code:1:
array(4) {
  'warning_count' =>
  int(0)
  'warnings' =>
  array(0) {
  }
  'error_count' =>
  int(1)
  'errors' =>
  array(1) {
    [23] =>
    string(47) "The timezone could not be found in the database"
  }
}
```

I need to find the exact format for this one before it get supported

**Comment by alexdebril** [comment]
```php
$format = "Y-m-d\TH:i:s.uvP";
```
works

**Comment by alexdebril** [comment]
@timokoesters the fix will be released in the next couple of hours, could you share with me the link to the issue in nextcloud news please ?
