### ISSUE TITLE
TypeError in Media::setUrl()

### ISSUE THREAD

**Issue by anoymouserver** [alexdebril/feed-io#281]
I'm getting the following error in the Nextcloud News app (nextcloud/news#691).
`TypeError: Argument 2 passed to FeedIo\Rule\Media::setUrl() must be of the type string, null given`

This seems to be caused by returning a string or null
https://github.com/alexdebril/feed-io/blob/122677baf80102dbb2782b6f3a213dc3c60f94fc/src/FeedIo/RuleAbstract.php#L75-L77
but `setUrl` function only accepting a string.
https://github.com/alexdebril/feed-io/blob/122677baf80102dbb2782b6f3a213dc3c60f94fc/src/FeedIo/Rule/Media.php#L66-L68

I've hotfixed it for me by also allowing null and checking it before calling the `UrlGenerator`.
```php
    protected function setUrl(MediaInterface $media, ?string $url, NodeInterface $node): void
    {
        $media->setUrl($url === null ? $url : $this->urlGenerator->getAbsolutePath($url, $node->getHost())); 
    }
```

_Edit:_
Invidious feeds have this behavior, for example. They have a `media:group` without a `media:content` inside. ([example feed](https://invidio.us/feed/channel/UCb3KY97ICfIkDJY_p6d7yig))

**Comment by anoymouserver** [comment]
The same problem happens some lines later with `getAttributeValue` which also could return null.
This is caused by feeds using `media:content` without an url attribute. ([example feed on Vimeo](https://vimeo.com/petzl/videos/rss))

**Comment by alexdebril** [comment]
Thank you very for this valuable feedback @anoymouserver ! 

The hotfix is on its way, I think it will released really soon (like today)
