### ISSUE TITLE
Control which things issue warnings

### ISSUE THREAD

**Issue by simonspa** [alexdebril/feed-io#293]
I am using `feed-io` as part of Nextcloud News and it works really great. Unfortunately, what's not working great is many of the feeds I am following - many of them seem temporarily unavailable from time to time resulting in cURL errors.

This results in hundreds of warnings being logged in my Nextcloud instance (News just passes a PSR-logger to feed-io) which makes spotting actual problems in the instance quite hard.

Is there a way of controlling which actions/results log a warning? Where would - from your perspective - be the appropriate place to catch these messages?

**Comment by alexdebril** [comment]
For now feed-io's logging is pretty simple: it writes all the messages in one channel so it's not made to be filtered. 

You can change the log's level but I guess you already did that before writing this issue. 

Not an issue that I intend to ignore but it's not a high priority for now. However I'm thinking about it sometimes and I'm still not clear on what to do with this. So let's make some progress with an open discussion before implementing this 🙂
