### ISSUE TITLE
getLink for items returns wrong URL

### ISSUE THREAD

**Issue by svbergerem** [alexdebril/feed-io#299]
For the feed https://www.process-one.net/feed/, `getLink()` for an item returns https://www.process-one.net/blog/eturnal-v1-0-0-say-hello-to-a-new-stun-turn-server/feed/ instead of https://www.process-one.net/blog/eturnal-v1-0-0-say-hello-to-a-new-stun-turn-server/.

The reason might be that in the atom feed there are multiple link elements. The first one is
```
<link rel="alternate" type="text/html" href="https://www.process-one.net/blog/eturnal-v1-0-0-say-hello-to-a-new-stun-turn-server/" />
```
and the last one is
```
<link rel="replies" type="application/atom+xml" href="https://www.process-one.net/blog/eturnal-v1-0-0-say-hello-to-a-new-stun-turn-server/feed/" thr:count="0"/>
```
which seems to be the one that is used by feed-io.

Related issue: https://github.com/nextcloud/news/issues/735

**Comment by alexdebril** [comment]
Hello

OK, I'll try to fix that soon
