### ISSUE TITLE
Can't parse feed whose syn:updateBase tag is set to pre-unix time

### ISSUE THREAD

**Issue by trougnouf** [alexdebril/feed-io#308]
This is related to https://github.com/nextcloud/news/issues/676
Example feed: http://export.arxiv.org/rss/cs.CV
Feeds whose syn:updateBase tag is very ancient (eg 1901) are not parsed by feed-io, and in turn RSS readers like NextCloud's.

**Comment by alexdebril** [comment]
the problem is not related to the pre-unix value, it's because the feed uses the RDF format. It's an old format that almost disappeared, that's why it's poorly supported by `feed-io`. Feel free to submit a pull request if you want to improve RDF support.

**Comment by alexdebril** [comment]
@trougnouf I owe you an apology: you were right about the time comparison issue...
