### ISSUE TITLE
cURL error 60: SSL certificate problem

### ISSUE THREAD

**Issue by dariopepe** [alexdebril/feed-io#309]
When reading feeds on some websites, cURL raises the SSL certificate error in the subject e.g: https://www.fiorentinanews.com/feed/ even if the feed is valid.
You need to specify in the guzzle client the following option to avoid the issue:

['verify' => false]

i've sorted out to fix the issue by adding to Factory class the following:

 array $clientConfig = [
            'builder' => 'GuzzleClient',
            'config' => ['verify' => false],
        ]

but it could be useful to have a method to turn off the ssl verification or to set a custom config on the client

**Comment by alexdebril** [comment]
Actually, it's already possible to configure Guzzle while instantiating feed-io:

```php
$feedIo = \FeedIo\Factory::create(['builder' => 'monolog'], ['builder' => 'GuzzleClient', 'config' => ['verify' => false]])->getFeedIo();
```

I must admit that it's far from easy and not very well documented, I'll add something about this in the README

**Comment by alexdebril** [comment]
new paragraph here: https://github.com/alexdebril/feed-io#configure-feed-io-using-the-factory
