### ISSUE TITLE
feed-io can't update https://web.dev/feed.xml

### ISSUE THREAD

**Issue by mogoh** [alexdebril/feed-io#313]
As the title says.

See also: https://github.com/nextcloud/news/discussions/976#discussioncomment-197047

**Comment by alexdebril** [comment]
See my response in nextcloud's issue

**Comment by mogoh** [comment]
Thanks.

**Comment by alexdebril** [comment]
I'm closing this issue as the root cause is a bug in the feed itself. It can't be solved with a harmless workaround so I prefer to contact the publisher and them to fix it instead.
