### ISSUE TITLE
Set LIMITto how many feeds to fetch

### ISSUE THREAD

**Issue by Ebest01** [alexdebril/feed-io#315]
Am using the Feed-io but seems there is NO Documentation on jhow to LIMIT the number of feeds.

Example, I have 4 RSS links and i would like to get only TWO feeds maximum per RSS link.

There is no much information as to how to achieve that.

-Please help

**Comment by alexdebril** [comment]
actually, you have to limit the output yourself. With a counter in the `for` loop or something like that, it's not something that will be supported by feed-io.

**Comment by Ebest01** [comment]
Ok Noted.

Thank you very much
