### ISSUE TITLE
feed-io.net CORS-Header 'Access-Control-Allow-Origin' missing

### ISSUE THREAD

**Issue by Grotax** [alexdebril/feed-io#325]
Currently it's not possible to use feed-io.net with a modern browser because https://api.feed-io.net/feed/discover is missing the CORS header.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

Example error from chromium:
```
Access to fetch at 'https://api.feed-io.net/feed/discover' from origin 'https://feed-io.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by alexdebril** [comment]
Woups, my bad I made an experiment a few days back and it didn't went well... Thanks for noticing that, the fix is applied and the build is on its way: https://hub.docker.com/repository/registry-1.docker.io/alexdebril/feed-io-api-fpm/builds/81553d15-47ab-4f45-96b0-ac25dd564805

**Comment by alexdebril** [comment]
Fixed ! thanks @Grotax :)

**Comment by Grotax** [comment]
https://api.feed-io.net/feed/consume still fails though

**Comment by alexdebril** [comment]
probably a cache issue with the browser, it worked for me with https://packagist.org/feeds/releases.atom and https://php.net/feed.atom

**Comment by Grotax** [comment]
True cleared the cache now it's working, thanks it's a helpful tool for the users of news to do some analysis by themselves :)
