### ISSUE TITLE
MediaInterface.getNodeName() should return nullable string

### ISSUE THREAD

**Issue by snomad** [alexdebril/feed-io#328]
All other getters in the MediaInterface are marked as ?string except getNodeName

It is currently marked as  
`public function getNodeName() : string;`

In certain cases, this yields a Throwable, 

TypeError {#3001
  #message: "Return value of FeedIo\Feed\Item\Media::getNodeName() must be of the type string, null returned"
  #code: 0
  #file: "....\vendor\debril\feed-io\src\FeedIo\Feed\Item\Media.php"
  #line: 58

**Comment by alexdebril** [comment]
Can you copy paste the code invoking this and the full stack trace please? The node's name cannot be empty, I need to know how it happened

**Comment by snomad** [comment]
Attached is txt file of XML doc that produces the error (just rename as .xml)

It is from a Bleacher Report feed: https://bleacherreport.com/articles/feed?tag_id=16

[bleacher report.txt](https://github.com/alexdebril/feed-io/files/6056966/bleacher.report.txt)

Error
Message: getNodeName error, Return value of FeedIo\Feed\Item\Media::getNodeName() must be of the type string, null returned  
file C:\dev\project\vendor\debril\feed-io\src\FeedIo\Feed\Item\Media.php 
line 58 
code 0  

First line of stack trace
C:\dev\project\app\Services\Rss\FeedItem.php(260): FeedIo\Feed\Item\Media->getNodeName()

In case it matters, $media->getType() returns null.

**Comment by alexdebril** [comment]
actually you're right. As the data is not initialized during the object's instantiation, so we can't guarantee that we have a value before calling the getter.

Fix is on its way
