### ISSUE TITLE
GeoRSS and GeoJson

### ISSUE THREAD

**Issue by boris-glumpler** [alexdebril/feed-io#358]
Hello,

I'd like to add some geo information to my feeds. In the case of RSS and Atom this would be following the [GeoRSS Simple standard](http://docs.opengeospatial.org/cs/17-002r1/17-002r1.html). For JsonFeed I'd like to add some [GeoJson](https://geojson.org/) data as an extension. Something along the lines of this:

```

"_geo_json": {
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [125.6, 10.1]
  },
  "properties": {
    "name": "Dinagat Islands"
  }
}
```

I've looked through the source a bit, but there doesn't seem to be a way to add some arbitrary data/extensions to feeds or feed items. Is this currently possible and if not, would something like a generic extension API make sense? 

Cheers!

**Comment by alexdebril** [comment]
Hi,

In the case of JSON the answer's simple: the formatter is monolithic so you'll need to extend it to add formatting rules like this.

In the case of XML based formats: I think (but I need to look at the code to confirm that) that you can add "Rules" to the "Standards" you want to extend. To do such, you would ->getStandard() from your FeedIo instance and add the rule to it.

Other lead : "OptionalField"  , it's a class you can use to add home-made structures like the one you want to implement.

I'll read again the code and get back to you.

Cheers

**Comment by boris-glumpler** [comment]
Alright, thanks for that! It looks like I can use `$feedIo->addStandard()` to override the standards. Mine will then just extend the built-in ones. In the case of `Json` I then need to override the `getFormatter()` method to return a GeoJson compatible formatter. For `Atom` and `Rss` I can then add rules by overriding the `buildItemRuleSet()` and `buildBaseRuleSet` methods. Should work ;)

**Comment by alexdebril** [comment]
Yes and I advise to choose a custom name for your standards, like "geo-json". As such, you will be able to use those names directly when calling FeedIo:: format ($feed, $standardName);

**Comment by boris-glumpler** [comment]
Alright, that all worked. Thanks for pointing me in the right direction!
