### ISSUE TITLE
v4 getContent also triggers the getDescription deprecation note

### ISSUE THREAD

**Issue by anoymouserver** [alexdebril/feed-io#359]
I just changed the deprecated calls from `getDescription` to `getContent` and `getSummary` for nextcloud/news#1303, but the deprecation warnings still occur, since `getContent()` itself calls `getDescription()` as fallback.
Any idea how to solve this, since we currently can't switch to v5 yet because of PHP 8. Otherwise the logs are flooded with unnecessary entries.

https://github.com/alexdebril/feed-io/blob/ab30d4698ba2481cb8785ea57a8cd3f60f6c475c/src/FeedIo/Feed/Item.php#L95-L108

<details><summary>PHP backtrace</summary>

```
#0  FeedIo\Feed\Item->getDescription() called at [/var/www/cloud/apps/news/vendor/debril/feed-io/src/FeedIo/Feed/Item.php:107]
#1  FeedIo\Feed\Item->getContent() called at [/var/www/cloud/apps/news/lib/Fetcher/FeedFetcher.php:270]
#2  OCA\News\Fetcher\FeedFetcher->buildItem() called at [/var/www/cloud/apps/news/lib/Fetcher/FeedFetcher.php:154]
```
</details>

**Comment by anoymouserver** [comment]
Maybe something like this:
```diff
     public function getContent(): ?string 
     {
-         return $this->content ?? $this->getDescription();
+         return $this->content ?? parent::getDescription();
     }
```

**Comment by alexdebril** [comment]
Hi @anoymouserver 

I'm fixing this right now, thanks for your feedback (and sorry for your file system!)

**Comment by anoymouserver** [comment]
No worries! Thanks for the quick response.

**Comment by alexdebril** [comment]
You can update to v4.9.6, it will be OK :)

**Comment by anoymouserver** [comment]
tested and works 👍
