### ISSUE TITLE
author is sometimes being merged with other fields

### ISSUE THREAD

**Issue by dingman** [alexdebril/feed-io#363]
In some circumstances, I'm seeing the author name of an item come through as `<name><title><site name>`

![image](https://user-images.githubusercontent.com/1911531/118278904-20972a00-b490-11eb-9920-c33926e3eb85.png)

Example feed to test with: https://blog.google/rss

**Comment by alexdebril** [comment]
It took me some time to accept this idea, but yes: Google exposes a buggy feed :smile: 

In the feed you've shared, we can see that the `author` tag is structured with 3 sub elements like in an Atom formatted feed. However, the feed indicates that its format is RSS 2.0 , which states that the `author` tags contains only a string ...

see: https://validator.w3.org/feed/docs/rss2.html#ltauthorgtSubelementOfLtitemgt

Mixing specifications is not something I'm willing to do in feed-io's roadmap, so I'm closing the issue. It can be re-opened by whoever wants to come with a well-designed way to support all specifications at once.
