### ISSUE TITLE
Create an RSS feed with content:encoded

### ISSUE THREAD

**Issue by ryadbkr** [alexdebril/feed-io#368]
We've been trying to create an RSS feed containing 
`<content:encoded><![CDATA[ <p> no luck ]]></content:encoded>` 

we've tried creating an element with the CDATA as content but it seems the CDATA tag is being encoded `(<content:encoded>&lt;![CDATA[),` hence it's not well interpreted by the RSS/XML parser,

Is using **CDATA** within `<content:encoded>` supported? If no are you planing on adding it.

Thanks

**Comment by alexdebril** [comment]
Hi,

No, it's not supported and I don't plan to do so. If you need that feature you can:
- build your own standard and add it in the Specification provided to FeedIo
- submit a Pull Request to make feed-io support it in its actual standards

But I'm not in favor of the second one. It's an edge-case, I prefer to avoid having to support it in the long run.
