### ISSUE TITLE
v4.9.10 requires PHP 8

### ISSUE THREAD

**Issue by anoymouserver** [alexdebril/feed-io#385]
Version 4.9.10 incorrectly requires PHP 8 (see https://packagist.org/packages/debril/feed-io#v4.9.10)
Also the release/tag v4.9.10 points to the same commit as v5.0.5 (0c2c92457a2c0e82ea63ab864012436cde4e931b)
Did you maybe tag the wrong branch?

refs nextcloud/news#1646

**Comment by alexdebril** [comment]
that's fixed with v4.9.11 , sorry for that ! I got confused while double-releasing compat with Symfony 7
