### ISSUE TITLE
Error_log flooding in version 4.9.8 on getDescription() vs getContent()

### ISSUE THREAD

**Issue by geoffsmiths** [alexdebril/feed-io#391]
There's a lot of `error_log()` flooding due to the depricated method `getDescription()` when using version 4.9.8. This method will be removed from future versions and instead we're required to install PHP8.0 or higher and use `getContent()`. 

Could you please remove the `error_log()` call in a hotfix for version 4.9.81?

**Comment by alexdebril** [comment]
you can use `getContent()` right away, what's preventing you from calling it ? https://github.com/alexdebril/feed-io/blob/release/4.9.x/src/FeedIo/Feed/Item.php#L105

**Comment by geoffsmiths** [comment]
Internal calls from the FeedIo package to `getDescription()` causes error_log() calls. This causes `error_log()` flooding in the logs. So, I'm not using `getDescription()` from my code, FeedIo does.

**Comment by geoffsmiths** [comment]
Hi, I have forked this repo and added a tag v4.9.81 with the replacements of the outdated calls to `getDescription()` to `getContent()`. See https://github.com/geoffsmiths/feed-io/releases/tag/v4.9.81

**Comment by alexdebril** [comment]
@geoffsmiths should be fixed in 4.9.13

**Comment by geoffsmiths** [comment]
> @geoffsmiths should be fixed in 4.9.13

Thank you @alexdebril for your effort. :)

**Comment by alexdebril** [comment]
You're welcome ! closing this, feel free to re-open the issue if you get another occurrences coming
