### ISSUE TITLE
Support Httplug

### ISSUE THREAD

**Issue by aschempp** [alexdebril/feed-io#398]
This library is currently hardcoded to Guzzle. It would be great to support http://httplug.io so any existing application could use their own implementation. For example in a Symfony project, one would most likely want to use `symfony/http-client`.

Let me know if you like the idea, I might be able to provide a PR 🙃

**Comment by alexdebril** [comment]
@aschempp it's now released in version 6.0 :rocket: 

Many thanks to @bezin ! :heart:
