### ISSUE TITLE
additionalFields as array

### ISSUE THREAD

**Issue by ivoba** [alexdebril/feed-io#6]
hi, i have integrated the lib in a project, works fine with most feeds, also with the optionalFields.

but i came across feeds with multiple elements of the same namespaced name like:

```xml
<media:thumbnail url="http://th06.deviantart.net/fs70/150/i/2015/056/5/3/spray_painting_abstract___inflamed_solo_by_airgone-d8jgg9c.jpg" height="100" width="150"/>            
<media:thumbnail url="http://th08.deviantart.net/fs70/300W/i/2015/056/5/3/spray_painting_abstract___inflamed_solo_by_airgone-d8jgg9c.jpg" height="200" width="300"/>            
<media:thumbnail url="http://th02.deviantart.net/fs70/200H/i/2015/056/5/3/spray_painting_abstract___inflamed_solo_by_airgone-d8jgg9c.jpg" height="200" width="300"/>            
<media:content url="http://fc01.deviantart.net/fs70/i/2015/056/5/3/spray_painting_abstract___inflamed_solo_by_airgone-d8jgg9c.jpg" height="683" width="1024" medium="image"/>
```

in the current implementation optionalFields is not an array or list, so the elements will override themselves.

i looked around a bit, but couldnt find the point where i could extend or change this.
maybe you can point me to where this can be done, i guess in the rulesets?

example feed is:
http://backend.deviantart.com/rss.xml?q=sort%3Atime+fractal&type=deviation

cheers

**Comment by alexdebril** [comment]
Hi,

Thank you for your bug report, this one is tough :)

I think you can override the OptionalField class, name it Thumbails and make it able to deal with arrays of thumbnails. Then, you'll need to add it to the standard's ruleset before parsing the feed.

I am not able to code right now, so I can't write the fix and test it immediately. Let me know if my suggestion works for you, I will try to handle this kind of node very soon.

Cheers

**Comment by ivoba** [comment]
The most simple solution for me was this in FeedIo\Feed\Item\OptionalFields:

     $this->data[$name][] = $value;

By making  $this->data twodimensional it wont override existings nodes.  
This would change the return type from string to array though.  

What do you think?

Another issue is that additional attributes get lost currently, like the height & width attributes.

**Comment by alexdebril** [comment]
Hi,

I'm thinking of an OptionalValue class to deal with arrays of nodes and store its attributes. Or something like that, it will be committed to close this issue.

Cheers

**Comment by alexdebril** [comment]
Hi,

Now in the 0.6.0 version you can do something like that : 

```php
foreach ( $item->getValue('media:thumbnail') as $thumbnail ) {
    echo $thumbail->getAttribute('url');
}
```

The documentation is not clear about it right now, but I will explain that further quite soon.

Cheers,

Alex
