### ISSUE TITLE
RSS Item PublicId is overridden by fixer

### ISSUE THREAD

**Issue by ruudvdd** [alexdebril/feed-io#82]
For the RSS standard:

At first the PublicId's of Items are the guid of the item. But after the PublicId fixer is finished, all PublicId properties of the parsed items contain the value of the link element, not allowing the user to access the guid anymore.

This is because the PublicId fixer checks whether the Feed object contains a PublicId. If not, it sets the PublicId property of the feed to the value of the link element and overrides the guid stored in the PublicId property of all item elements with the link elements of those items.

Is it ok to add a PublicId Rule to the Feed RuleSet so the RSS channel link element will be set as Feed PublicId and the fixer will skip, so the dev has access to the guid?

**Comment by alexdebril** [comment]
I fixed this in this commit : https://github.com/alexdebril/feed-io/commit/da7c6454fce44182eb20913b77809dc647aacf10

**Comment by ruudvdd** [comment]
Great! Thanks!
